#!/usr/bin/env python

numbers = [0, 88, 34, 2678, -3, -88, 123, 4, 8, 9, 22, 354, 74]
# the list index syntax arr[1:5] means "from 1-5, excluding 5"

def sortlist(arr):
    x = len(arr)
    
    while x > 0:
        minimum = min(arr[0:x])
        minimumIndex = arr.index(minimum)
        arr.append(arr[minimumIndex])
        del arr[minimumIndex]
        x = x-1

print ". input .\t" + str(len(numbers)) + " integers"
print "\t\t" + str(numbers)
print ". output .\t"
sortlist(numbers)
print "\t\t" + str(numbers)
